[package]
name = "test-rs"
version = "0.1.0"
authors = ["Konstantin Gorodinskii <mail@konstantin.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.0"
regex = "1"
